set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(OUTPUT_DIRECTORY output)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${OUTPUT_DIRECTORY})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${OUTPUT_DIRECTORY})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${OUTPUT_DIRECTORY})

set(VOSK_LIBRARY_DIR vosk-win64-0.3.42)
set(VOSK_DIR ${CMAKE_SOURCE_DIR}/${VOSK_LIBRARY_DIR})

file(GLOB VOSK_LIBRARIES ${VOSK_DIR}/*.dll)
message("-- VOSK_LIBRARIES: ${VOSK_LIBRARIES}")

file(COPY ${VOSK_LIBRARIES} DESTINATION ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})

include_directories(${VOSK_DIR})
link_directories(${VOSK_DIR})
